NerdStore.WebApp.MVC/Models/ErrorViewModel.cs
using System;

namespace NerdStore.WebApp.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NerdStore.WebApp.MVC/Controllers/Admin/AdminProdutosController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NerdStore.Catalogo.Application.Services;
using NerdStore.Catalogo.Application.ViewModels;

namespace NerdStore.WebApp.MVC.Controllers.Admin
{
    public class AdminProdutosController : Controller
    {
        private readonly IProdutoAppService _produtoAppService;

        public AdminProdutosController(IProdutoAppService produtoAppService)
        {
            _produtoAppService = produtoAppService;
        }

        [HttpGet]
        [Route("admin-produtos")]
        public async Task<IActionResult> Index()
        {
            return View(await _produtoAppService.ObterTodos());
        }

        [Route("novo-produto")]
        public async Task<IActionResult> NovoProduto()
        {
            return View(await PopularCategorias(new ProdutoViewModel()));
        }

        [Route("novo-produto")]
        [HttpPost]
        public async Task<IActionResult> NovoProduto(ProdutoViewModel produtoViewModel)
        {
            if (!ModelState.IsValid) return View(await PopularCategorias(produtoViewModel));

            await _produtoAppService.AdicionarProduto(produtoViewModel);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("editar-produto")]
        public async Task<IActionResult> AtualizarProduto(Guid id)
        {
            return View(await PopularCategorias(await _produtoAppService.ObterPorId(id)));
        }

        [HttpPost]
        [Route("editar-produto")]
        public async Task<IActionResult> AtualizarProduto(Guid id, ProdutoViewModel produtoViewModel)
        {
            var produto = await _produtoAppService.ObterPorId(id);
            produtoViewModel.QuantidadeEstoque = produto.QuantidadeEstoque;

            ModelState.Remove("QuantidadeEstoque");
            if (!ModelState.IsValid) return View(await PopularCategorias(produtoViewModel));

            await _produtoAppService.AtualizarProduto(produtoViewModel);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("produtos-atualizar-estoque")]
        public async Task<IActionResult> AtualizarEstoque(Guid id)
        {
            return View("Estoque", await _produtoAppService.ObterPorId(id));
        }

        [HttpPost]
        [Route("produtos-atualizar-estoque")]
        public async Task<IActionResult> AtualizarEstoque(Guid id, int quantidade)
        {
            if (quantidade > 0)
            {
                await _produtoAppService.ReporEstoque(id, quantidade);
            }
            else
            {
                await _produtoAppService.DebitarEstoque(id, quantidade);
            }

            return View("Index", await _produtoAppService.ObterTodos());
        }

        private async Task<ProdutoViewModel> PopularCategorias(ProdutoViewModel produto)
        {
            produto.Categorias = await _produtoAppService.ObterCategorias();
            return produto;
        }
    }
}

NerdStore.WebApp.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NerdStore.WebApp.MVC.Models;

namespace NerdStore.WebApp.MVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NerdStore.WebApp.MVC/Views/AdminProdutos/AtualizarProduto.cshtml
@model NerdStore.Catalogo.Application.ViewModels.ProdutoViewModel

@{
    ViewData["Title"] = "AtualizarProduto";
}

<h1>Editar Produto</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AtualizarProduto">
            <div asp-validation-summary="All" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label class="control-label">Categoria</label>
                <select asp-for="CategoriaId" class="form-control" asp-items="@(new SelectList(Model.Categorias, "Id", "Nome"))">
                    <option></option>
                </select>

                <span asp-validation-for="CategoriaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input asp-for="Imagem" class="form-control" />
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Altura" class="control-label"></label>
                <input asp-for="Altura" class="form-control" />
                <span asp-validation-for="Altura" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Largura" class="control-label"></label>
                <input asp-for="Largura" class="form-control" />
                <span asp-validation-for="Largura" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Profundidade" class="control-label"></label>
                <input asp-for="Profundidade" class="form-control" />
                <span asp-validation-for="Profundidade" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Atualizar" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

NerdStore.WebApp.MVC/Views/AdminProdutos/Estoque.cshtml
@model NerdStore.Catalogo.Application.ViewModels.ProdutoViewModel
@{
    ViewData["Title"] = "Editar Produto";
}

<div class="container">
    <div class="row">
        <div class="col-xs-4 item-photo">
            <img width="400" height="400" src="~/Images/@Model.Imagem" />
        </div>
        <div class="col-xs-5" style="border:20px solid white">
            <h3>@Model.Nome</h3>

            <h6 class="title-price"><small>OFERTA</small></h6>
            <h3 style="margin-top:0px;">@Model.Valor.ToString("C")</h3>

            <p>Apenas @Model.QuantidadeEstoque em estoque!</p>
            <p>@Model.Descricao</p>

            <div class="section" style="padding-bottom:20px;">
                <form method="post" asp-controller="AdminProdutos" asp-action="AtualizarEstoque">
                    <input type="hidden" id="Id" name="Id" value="@Model.Id" />
                    <input type="text" id="quantidade" name="quantidade" />
                    <button class="btn btn-info">Atualizar Estoque</button>
                </form>
            </div>
        </div>
    </div>
</div>

NerdStore.WebApp.MVC/Views/AdminProdutos/Index.cshtml
@model IEnumerable<NerdStore.Catalogo.Application.ViewModels.ProdutoViewModel>

@{
    ViewData["Title"] = "Vitrine";
}
<style>
    h4 {
        font-weight: 600;
    }

    p {
        font-size: 12px;
        margin-top: 5px;
    }

    .price {
        font-size: 30px;
        margin: 0 auto;
        color: #333;
    }

    .right {
        float: right;
        border-bottom: 2px solid #4B8E4B;
    }

    .thumbnail {
        opacity: 0.70;
        -webkit-transition: all 0.5s;
        transition: all 0.5s;
    }

        .thumbnail:hover {
            opacity: 1.00;
            box-shadow: 0px 0px 10px #4bc6ff;
        }

    .line {
        margin-bottom: 5px;
    }

    @@media screen and (max-width: 770px) {
        .right {
            float: left;
            width: 100%;
        }
    }

    .product_view .modal-dialog {
        max-width: 800px;
        width: 100%;
    }

    .pre-cost {
        text-decoration: line-through;
        color: #a5a5a5;
    }

    .space-ten {
        padding: 10px 0;
    }
</style>
<div class="container">

    <h1>Administração de Produtos</h1>
    <hr />
    <div class="row">
        <a asp-controller="AdminProdutos" asp-action="NovoProduto" class="btn btn-success right">+ Adicionar Novo</a>
    </div>
    <hr />
    <div class="row">
        <!-- BEGIN PRODUCTS -->
        @{
            foreach (var produto in Model.OrderBy(p => p.CategoriaId))
            {
            <div class="col-md-3 col-sm-6">
                <span class="thumbnail">
                    <img width="200" height="200" src="~/Images/@produto.Imagem" />
                    <h4>@produto.Nome</h4>
                    <p>@produto.QuantidadeEstoque em estoque</p>
                    <p>@produto.Descricao</p>
                    <p class="price">@produto.Valor.ToString("C")</p>
                    <hr class="line">
                    <div class="row">
                        <a asp-controller="AdminProdutos" asp-action="AtualizarProduto" asp-route-id="@produto.Id" class="btn btn-success right">Editar</a> &nbsp;
                        <a asp-controller="AdminProdutos" asp-action="AtualizarEstoque" asp-route-id="@produto.Id" class="btn btn-info right">Estoque</a>
                    </div>
                </span>
            </div>
            }
        }

        <!-- END PRODUCTS -->
    </div>
</div>

NerdStore.WebApp.MVC/Views/AdminProdutos/NovoProduto.cshtml
@model NerdStore.Catalogo.Application.ViewModels.ProdutoViewModel

@{
    ViewData["Title"] = "NovoProduto";
}

<h1>Novo Produto</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="NovoProduto">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label class="control-label">Categoria</label>
                <select asp-for="CategoriaId" class="form-control" asp-items="@(new SelectList(Model.Categorias, "Id", "Nome"))">
                    <option></option>
                </select>

                <span asp-validation-for="CategoriaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input asp-for="Imagem" class="form-control" />
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="QuantidadeEstoque" class="control-label"></label>
                <input asp-for="QuantidadeEstoque" class="form-control" />
                <span asp-validation-for="QuantidadeEstoque" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Altura" class="control-label"></label>
                <input asp-for="Altura" class="form-control" />
                <span asp-validation-for="Altura" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Largura" class="control-label"></label>
                <input asp-for="Largura" class="form-control" />
                <span asp-validation-for="Largura" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Profundidade" class="control-label"></label>
                <input asp-for="Profundidade" class="form-control" />
                <span asp-validation-for="Profundidade" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

NerdStore.WebApp.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NerdStore.WebApp.MVC/Views/Shared/_Layout.cshtml
﻿<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NerdStore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Vitrine" asp-action="Index">NerdStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminProdutos" asp-action="Index">Admin</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - NerdStore.WebApp.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>